"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, ShieldCheck } from "lucide-react";
import { apiRequest, UserSummary } from "@/lib/api";

type CrisisAlert = {
  id: number;
  user: UserSummary;
  counsellor: UserSummary | null;
  trigger: string;
  source: string;
  status: string;
  notes: string;
  created_at: string;
};

export default function CounsellorPage() {
  const [alerts, setAlerts] = useState<CrisisAlert[]>([]);
  const [error, setError] = useState("");

  async function loadAlerts() {
    try {
      setAlerts(await apiRequest<CrisisAlert[]>("/crisis-alerts/"));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to load alerts");
    }
  }

  useEffect(() => {
    loadAlerts();
  }, []);

  async function updateAlert(id: number, status: string) {
    try {
      await apiRequest<CrisisAlert>("/crisis-alerts/", {
        method: "PATCH",
        body: { id, status },
      });
      await loadAlerts();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unable to update alert");
    }
  }

  return (
    <div className="mx-auto max-w-6xl space-y-6">
      <header>
        <h1 className="text-3xl font-bold text-slate-950">Counsellor Intervention</h1>
        <p className="text-sm text-slate-600">Review crisis and low-mood alerts generated by the backend safety layer.</p>
      </header>

      {error && <p className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}

      <section className="rounded-md border border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-5 py-4">
          <h2 className="flex items-center gap-2 font-semibold text-slate-900">
            <AlertTriangle className="h-5 w-5 text-red-600" />
            Alerts
          </h2>
        </div>
        <div className="divide-y divide-slate-100">
          {alerts.length === 0 && <p className="p-5 text-sm text-slate-500">No alerts found.</p>}
          {alerts.map((alert) => (
            <div key={alert.id} className="grid gap-4 p-5 lg:grid-cols-[1fr_auto]">
              <div>
                <p className="font-semibold text-slate-950">{alert.user.email}</p>
                <p className="mt-1 text-sm text-slate-600">Source: {alert.source} | Trigger: {alert.trigger}</p>
                <p className="mt-1 text-sm text-slate-500">{new Date(alert.created_at).toLocaleString()}</p>
              </div>
              <div className="flex items-start gap-2">
                <span className="rounded-md bg-red-50 px-2 py-1 text-xs font-semibold capitalize text-red-700">{alert.status}</span>
                {alert.status !== "resolved" && (
                  <>
                    <button onClick={() => updateAlert(alert.id, "reviewing")} className="rounded-md bg-slate-800 px-3 py-1 text-xs font-semibold text-white">Review</button>
                    <button onClick={() => updateAlert(alert.id, "resolved")} className="inline-flex items-center gap-1 rounded-md bg-green-600 px-3 py-1 text-xs font-semibold text-white">
                      <ShieldCheck className="h-3 w-3" />
                      Resolve
                    </button>
                  </>
                )}
              </div>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
