# Generated by Django 6.0.4 on 2026-06-08 10:49

from django.db import migrations, models


def clear_journal_rows(apps, schema_editor):
    JournalEntry = apps.get_model("dashboard", "JournalEntry")
    JournalEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_crisisalert_appointment_directmessage'),
    ]

    operations = [
        migrations.RunPython(clear_journal_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='journalentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
