# Generated by Django 6.0.5 on 2026-06-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_institution_user_institution'),
        ('dashboard', '0004_alter_journalentry_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicontext',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_contexts', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='crisisalert',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crisis_alerts', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='auth_app.institution'),
        ),
        migrations.AddField(
            model_name='resource',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='auth_app.institution'),
        ),
    ]
