# Generated by Codex on 2026-05-29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0005_user_groups_user_is_superuser_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("counsellor", "Counsellor"),
                    ("admin", "Admin"),
                ],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="assigned_counsellor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "counsellor"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_students",
                to="auth_app.user",
            ),
        ),
    ]
